[versions]
agp = "8.9.1"
gson = "2.10.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
loggingInterceptor = "4.11.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
materialCalendarview = "2.0.1"
materialCalendarviewVersion = "2.0.1"
materialVersion = "1.6.0"
mockitoCore = "4.3.1"
navigationFragment = "2.5.3"
retrofit = "2.9.0"
rules = "1.0.2"

[libraries]
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material-calendarview = { module = "com.github.prolificinteractive:material-calendarview", version.ref = "materialCalendarview" }
material-v160 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
prolificinteractive-material-calendarview = { module = "com.prolificinteractive:material-calendarview", version.ref = "materialCalendarviewVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rules = { module = "com.android.support.test:rules", version.ref = "rules" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

